hello = [
"Welcome to Zutocraft, brave adventurer! Looking to craft something magnificent today? I can’t wait to help you!",
"Greetings! Are you ready to turn some raw materials into a masterpiece? Let’s get crafting!",
"Welcome to the guild! What can I assist you with today? I’ve been honing my skills, and I’m eager to share what I know!",
"Hiya! Did you come for some armor? I can help you craft something that’ll shine on the battlefield!",
"Welcome! I’m Zudi, your enthusiastic crafting companion! What item are you dreaming of creating?",
"Greetings, adventurer! Are you ready to transform some materials into armor? I’m here to help you every step of the way!",
"Welcome to Zutocraft! I hope you’re ready to create something epic! What’s on your crafting wishlist?",
"Hi, there! I’ve been waiting for someone like you! Let’s get crafting! Do you have a specific item in mind?",
"Welcome! I’ve been working on some new techniques! What kind of gear do you need? Let’s craft something special!",
"Hiya! Your timing is perfect! I’ve been itching to craft! What can I help you make today?",
"Welcome to the Zutocraft guild! I’m thrilled to see you! Ready to turn some ordinary materials into extraordinary gear?",
"Ah, adventurer! Just the person I wanted to see! Let’s turn those raw materials into something truly remarkable. What can I craft for you today?",
"Hello there! The guild is bustling with energy today. What are you looking to create? I’m excited to help you make it happen!",
"Welcome, friend! Looking for some finely crafted armor or maybe a new weapon? I’ve got plenty of ideas, and I’d love to help you get started!",
"Oh, you’ve come to the right place! Zutocraft is where the magic happens—quite literally, sometimes! What can I help you forge today?",
"Greetings, adventurer! I hope you’re ready to craft something legendary. I’m here to lend a hand with whatever you need!",
"Ah, I’ve been waiting for someone like you! The forge is hot, the materials are ready, and I’m eager to help! What can we create today?",
"Hello! What can I do for you today? Whether it’s plate armor or a finely stitched cloak, I’m ready to craft something unforgettable!",
"Welcome, welcome! Are you here to create something that will dazzle both allies and foes alike? Let’s get to work on your masterpiece!",
"Oh, this is exciting! What sort of gear are you thinking of today? I’ve got some fresh ideas that could make it even more spectacular!",
"Hey there! You’ve come to the right place if you’re looking for craftsmanship at its finest! Let’s make something that’ll stand the test of time."
]

who_are_you = [
"Hey there! I'm Zudi, the friendly face of Zutocraft, ready to assist with all your crafting!",
"Oh, hello! Zudicraft's the name, but Zudi works too! Here to help with your crafting needs!",
"Hi! I’m Zudi, your crafting expert at Zutocraft. What can I make for you today?",
"Greetings! I'm Zudi, always happy to lend a hand with crafting at Zutocraft!",
"Hey, adventurer! I’m Zudicraft, or Zudi for short! What can I craft for you today?",
"Hiya! Zudi’s the name, and crafting’s my game here at Zutocraft. How can I help?",
"Hey! I’m Zudi, here to assist with all your crafting needs at the Zutocraft guild!",
"Hello, adventurer! I’m Zudicraft, but call me Zudi! What crafting project do you have?",
"Hi there! I’m Zudi, your go-to for crafting here at Zutocraft. Need something made?",
"Greetings! Zudi’s the name, and I’m here to craft up a storm at Zutocraft!",
"Hey! I’m Zudi, the friendly face of crafting at Zutocraft. What can I do for you?",
"Hi! I’m Zudicraft, or Zudi if you like! Let’s make something amazing together at Zutocraft!",
"Oh, hello! I’m Zudi, your crafting assistant here at Zutocraft. Need a hand?",
"Hey there! I’m Zudi, here to craft whatever you need at Zutocraft. How can I assist?",
"Hello! I’m Zudicraft, or just Zudi. Crafting is what I do best here at Zutocraft!",
"Hi! I’m Zudi, and I’m always excited to help with crafting at the Zutocraft guild!",
"Hey! I’m Zudi, crafting enthusiast at Zutocraft! What can I make for you today?"
]

what_are_you_doing_here = [
"Just getting the hang of things here! Still learning the ropes at Zutocraft.",
"Oh, I’m still catching up! New to the guild, but eager to help however I can.",
"Learning all I can at Zutocraft! Every day’s a new lesson.",
"I’m still figuring out my way around, but I’m ready to jump in where needed!",
"Still new around here, so I’m learning as much as I can!",
"Just getting started at Zutocraft and soaking up all the crafting knowledge!",
"Still getting used to the workshop, but I’m excited to be here!",
"Catching up on the guild’s ways, but I’m eager to prove myself!",
"Learning the ropes, but I’m ready to help however I can!",
"Still a bit fresh here, but every day I’m learning something new!",
"Getting the hang of crafting at Zutocraft, one day at a time!",
"I’m still picking up the guild's tricks, but I’m always ready to assist!",
"Just finding my feet here, but I love being part of the team!",
"I’m still figuring out how everything works, but I’m getting there!",
"New to the guild, and there’s so much to learn! But I’m loving it.",
"Still learning the craft, but eager to help anyone who needs it!",
"I’m catching up on all the guild secrets, but I’m here to lend a hand!",
"Just starting out at Zutocraft, but ready to assist however I can!"
]